# Generated by Django 4.2.14 on 2024-07-31 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("galaxy", "0055_galaxy_role_defs_to_dab_defs"),
    ]

    '''
    operations = [
        migrations.CreateModel(
            name="OrganizationResourcesView",
            fields=[
                (
                    "organization",
                    models.ForeignKey(
                        db_column="org_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="galaxy.organization",
                    ),
                ),
            ],
            options={
                "db_table": "galaxy_dab_organization_resources_view",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TeamResourcesView",
            fields=[
                (
                    "team",
                    models.ForeignKey(
                        db_column="team_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="galaxy.team",
                    ),
                ),
            ],
            options={
                "db_table": "galaxy_dab_team_resources_view",
                "managed": False,
            },
        ),
    ]
    '''

    operations = []
